VisualforcePage1/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>ClassTeacher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ClassTeacher</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DetailedDescription__c</fullName>
        <label>DetailedDescription</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MaxSize__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MaxSize</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MyCount__c</fullName>
        <label>MyCount</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NumberOfStudents__c</fullName>
        <label>NumberOfStudents</label>
        <summaryForeignKey>Student__c.Class__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VisualforcePage1/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>Sex</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Enrollment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VisualforcePage1/src/classes/ClassesSelector.cls
public class ClassesSelector extends fflib_SObjectSelector{
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField>{
            Class__c.Id,
            Class__c.Name,
            Class__c.NumberOfStudents__c,
            Class__c.MaxSize__c,    
            Class__c.DetailedDescription__c,    
            Class__c.Fee__c,    
            Class__c.MyCount__c,
            Class__c.ClassTeacher__c
        };
    }
    public Schema.SObjectType getSObjectType(){
        return Class__c.SObjectType;
    }
    public Map<Id, Class__c> selectAllAsMap(){
        Map<Id, Class__c> classMap = new Map<Id, Class__c>(); 
        Database.QueryLocatorIterator iterate =  queryLocatorAllClasses().iterator();
        while(iterate.hasNext()){
            Class__c classInstance = (Class__c)iterate.next();
            classMap.put(classInstance.Id, classInstance);
        }
        return classMap;
    }
    public Database.QueryLocator queryLocatorAllClasses(){
       return Database.getQueryLocator(
          newQueryFactory().toSOQL()
       );
    }
    public List<Class__c> selectById(Set<ID> idSet){
        return (List<Class__c>) selectSObjectsById(idSet);
    }
    public Map<Id, Integer> selectStudentCountByClassId(Set<Id> classIdSet){
        Map<Id, Integer> studentClassMap = new Map<Id, Integer>();
        String query = String.format(
            'SELECT {0}, (SELECT Id FROM Students__r) from {1} ' + 
            'WHERE Id IN :classIdSet ',
            new List<String>{ getFieldListString(), getSObjectName() } );
        
        List<Class__c> classList = Database.query(query);
        
        for(Class__c cm : classList){
            studentClassMap.put(cm.Id, cm.Students__r.size());
        }
        return studentClassMap;
    }
    public Map<Id, Integer> selectFemaleStudentCountByClassId(Set<Id> classIdSet){
        Map<Id, Integer> studentClassMap = new Map<Id, Integer>();
        String Female = 'Female';
        String query = String.format(
            'SELECT {0}, (SELECT Id FROM Students__r WHERE Sex__c = :\'Female\') from {1} ' + 
            'WHERE Id IN :classIdSet ',
            new List<String>{ getFieldListString(), getSObjectName() } );
        
        List<Class__c> classList = Database.query(query);
        
        for(Class__c cm : classList){
            studentClassMap.put(cm.Id, cm.Students__r.size());
        }
        return studentClassMap;
    }

}