VisualforcePage1/src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VisualforcePage1/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Last_Name__c  &amp; IF(First_Name__c = null, &quot;&quot;, &quot;, &quot; &amp; First_Name__c)</formula>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Enrollment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestClasses/src/classes/Classes.cls
public class Classes {
    public static List<Student__c> getStudentsByClassId(Id classId){
        return [SELECT name__c FROM Student__c WHERE Class__r.Id = :classId];
    }
    
    public static Map<Class__c, Set<Student__c>> getClassMap(){
        List<Class__c> listOfClasses= [SELECT Id, (SELECT Id FROM Students__r) FROM Class__c];
        Map<Class__c, Set<Student__c>> classMap = new Map<Class__c, Set<Student__c>>();
        for(Class__c classVar : listOfClasses){
            Set<Student__c> setOfStudents = new Set<Student__c>();
            for(Student__c student : classVar.Students__r){
                setOfStudents.add(student);
            }
            classMap.put(classVar, setOfStudents);
        }
        return classMap;
    }
}