VisualforcePage1/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>MaxSize__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MaxSize</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VisualforcePage1/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>Sex</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Enrollment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestClasses/src/classes/TestStudentExtension.cls
@isTest
private class TestStudentExtension {
	@testSetup
    static void setup(){
        Class__c classInstance = new Class__c(Name = 'TestClass', MaxSize__c = 10);
        insert classInstance;
        Student__c student = new Student__c(Last_Name__c = 'LastStudent', Sex__c = 'Male', Class__c = classInstance.Id);
        insert student;
    }
    @isTest
    static void testPDFAttachment(){
        Student__c student = [SELECT Id, Name FROM Student__c WHERE Last_Name__c LIKE 'LastStudent%' LIMIT 1];
    	ApexPages.StandardController stdController = new ApexPages.StandardController(student);
        StudentExtension extension = new StudentExtension(stdController);
        Blob content = Blob.valueOf('UNIT.TEST');
        extension.attachPDF();
        System.assert([SELECT Id FROM Attachment WHERE parentId = :student.Id].size() != 0);
    }
    @isTest
    static void testDeletionOfPDFAttachment(){
        Student__c student = [SELECT Id, Name FROM Student__c WHERE Last_Name__c LIKE 'LastStudent%' LIMIT 1];
    	ApexPages.StandardController stdController = new ApexPages.StandardController(student);
        StudentExtension extension = new StudentExtension(stdController);
        Blob content = Blob.valueOf('UNIT.TEST');
        extension.attachPDF();
        Attachment attach = [SELECT Id, Name FROM Attachment WHERE parentId = :student.Id LIMIT 1];
        System.assert(attach != null);
        extension.deletePreviousAttachment(attach.Name);
        System.assert([SELECT Id, Name FROM Attachment WHERE parentId = :student.Id].size() == 0);
    }
}