VisualforcePage1/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>MaxSize__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MaxSize</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VisualforcePage1/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>Sex</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Enrollment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestClasses/src/classes/TestClass.cls
@isTest
private class TestClass {
    @isTest
    static void testStudentsByClassId(){
        Class__c cl = new Class__c(Name = 'V', MaxSize__c = 30);
        insert cl;
        Id classId = cl.Id;
        
        List<Student__c> listOfStudents = new List<Student__c>();
        for(Integer numberOfStudents = 0; numberOfStudents < 30; numberOfStudents++){
            Student__c student = new Student__c(
                First_Name__c = 'First'+numberOfStudents,
                Last_Name__c = 'Last'+numberOfStudents,
                Sex__c = 'Male',
                Class__c = classId
            );
            listOfStudents.add(student);
        }
        insert listOfStudents;
        System.assertEquals(30, ((List<Student__c>)Classes.getStudentsByClassId(cl.Id)).size());
    }
    @isTest
    static void testStudentsOfAllClasses(){
        List<Class__c> listOfClasses = new List<Class__c>();
        List<Student__c> listOfStudents = new List<Student__c>();
        for(Integer numberOfClasses = 0; numberOfClasses < 3; numberOfClasses++ ){
            Class__c cl = new Class__c(Name = 'class'+numberOfClasses, MaxSize__c = 30);
            listOfClasses.add(cl);
        }
        insert listOfClasses;
        
        for(Integer numberOfClasses = 0; numberOfClasses < 3; numberOfClasses++ ){
            Class__c cl = listOfClasses[numberOfClasses];
            
            for(Integer numberOfStudents = 0; numberOfStudents < 30; numberOfStudents++){
                Student__c student = new Student__c(
                    First_Name__c = 'First'+numberOfClasses+' '+numberOfStudents,
                    Last_Name__c = 'Last'+numberOfClasses+' '+numberOfStudents,
                    Sex__c = 'Male',
                    Class__c = cl.Id
                );
                listOfStudents.add(student);
            }
        }
        insert listOfStudents;
        
        Map<Class__c, Set<Student__c>> resultMap = new Map<Class__c, Set<Student__c>>(Classes.getClassMap());
        System.assertEquals(3, resultMap.size());
    }
}