VisualforcePage1/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>MaxSize__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MaxSize</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VisualforcePage1/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>Sex</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Enrollment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestClasses/src/classes/TestTriggerForFemaleStudentsInClass.cls
@isTest
private class TestTriggerForFemaleStudentsInClass {
    private static List<Class__c> listOfClasses = new List<Class__c>();
    @isTest
    static void testDeletionForClassWithMoreThanOneFemaleStudents(){
        for(Integer numberOfClasses = 0; numberOfClasses < 5; numberOfClasses++){
            Class__c classInstance = new Class__c(Name = ''+(numberOfClasses+1), MaxSize__c = 10);
            listOfClasses.add(classInstance);
        }
        insert listOfClasses;
        List<Student__c> listOfStudents = new List<Student__c>();
        for(Class__c classInstance : listOfClasses){
            for(Integer numberOfstudents = 0; numberOfstudents < 5; numberOfstudents++){
                Student__c student = new Student__c(Last_Name__c = 'st'+(numberOfstudents+1), Sex__c = 'Female', class__c = classInstance.Id);
                listOfStudents.add(student);
            }
            for(Integer numberOfstudents = 0; numberOfstudents < 5; numberOfstudents++){
                Student__c student = new Student__c(Last_Name__c = 'st'+(numberOfstudents+1), Sex__c = 'Male', class__c = classInstance.Id);
                listOfStudents.add(student);
            }
        }
        insert listOfStudents;
        Test.startTest();
        Database.DeleteResult[] result = Database.delete(listOfClasses, false);
        Test.stopTest();
        for(Database.DeleteResult res : result){
            System.assert(!res.isSuccess());
            System.assert(res.getErrors().size() > 0 );
            System.assertEquals('Cannot delete this class. More than one female students study here',res.getErrors()[0].getMessage());
        }
    }
    @isTest
    static void testDeletionForClassWithLessFemaleStudents(){
        List<Student__c> listOfStudents = new List<Student__c>();
        for(Class__c classInstance : listOfClasses){
            for(Integer numberOfstudents = 0; numberOfstudents < 5; numberOfstudents++){
                Student__c student = new Student__c(Last_Name__c = 'st'+(numberOfstudents+1), Sex__c = 'Male', class__c = classInstance.Id);
                listOfStudents.add(student);
            }
        }
        insert listOfStudents;
        Test.startTest();
        Database.DeleteResult[] result = Database.delete(listOfClasses, false);
        Test.stopTest();
        for(Database.DeleteResult res : result){
            System.assert(res.isSuccess());
        }
    }
}