VisualforcePage1/src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Last_Name__c  &amp; IF(First_Name__c = null, &quot;&quot;, &quot;, &quot; &amp; First_Name__c)</formula>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Enrollment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WebServices/src/classes/StudentsDetailController.cls
public class StudentsDetailController {
    public List<Student__c> listOfStudents { get; set; }
    public Id selectedStudent { get; set; }
    
    public StudentsDetailController(){
        listOfStudents = new StudentsSelector().getListOfStudents();
    }
    public List<SelectOption> getItems(){
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('null', '---None---'));
        for(Student__c student : listOfStudents){
            options.add(new SelectOption(student.Id, student.Name__c));
        }
        return options;
    }
}