Triggers/src/objects/CityManager__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CityManagers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CityManager</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>CityManager ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CityManagers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Triggers/src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Triggers/src/classes/Loans.cls
public class Loans extends fflib_SObjectDomain {

    public Loans(List<Loan__c> sObjectList) {
        super(sObjectList);
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new Loans(sObjectList);
        }
    }
    public override void onBeforeInsert() {
       	Set<String> citySet = new Set<String>();
        for(Loan__c loan : (List<Loan__c>) Records) {
            if(loan.City__c != null){
                citySet.add(loan.City__c);
            }
        }
        Map<String, CityManager__c> cityManagerMap = new Map<String, CityManager__c>();
        cityManagerMap = new CityManagersSelector().selectByCity(citySet);
        for(Loan__c loan : (List<Loan__c>) Records) {
            if(loan.City__c != null){
                String cityInLowerCase = loan.City__c.toLowerCase();
                if(cityManagerMap.containsKey(cityInLowerCase)){
                    loan.Manager__c = cityManagerMap.get(cityInLowerCase).Manager__c;
                }
            }
        }
    }
}