Triggers/src/objects/CityManager__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CityManagers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CityManager</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>CityManager ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CityManagers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Triggers/src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestClasses/src/classes/TestLoansTrigger.cls
@isTest
private class TestLoansTrigger {
    @isTest
    static void testTriggerBeforeInsert(){
        List<Loan__c> listOfLoans = new List<Loan__c>();
        CityManager__c cityManager = new CityManager__c(Manager__c = UserInfo.getUserId(), City__c = 'Jaipur');
        insert cityManager;
        for(Integer loanCount = 0; loanCount < 5; loanCount++){
            Loan__c loan = new Loan__c(Name = 'L'+loanCount, City__c = 'Jaipur');
            listOfLoans.add(loan);
        }
        for(Loan__c loan : listOfLoans){
            System.assert(loan.Manager__c == null);
        }
        Test.startTest();
        insert listOfLoans;
        Test.stopTest();
        System.assertEquals(UserInfo.getUserId(), [SELECT Manager__c FROM Loan__c WHERE Name LIKE 'L%' LIMIT 1].Manager__c);
    }
}