VisualforcePage2/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <label>Product Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Accessories</fullName>
                </value>
                <value>
                    <fullName>Books</fullName>
                </value>
                <value>
                    <fullName>Clothing</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Footwear</fullName>
                </value>
                <value>
                    <fullName>Home and Furniture</fullName>
                </value>
                <value>
                    <fullName>Luggage and Travel</fullName>
                </value>
                <value>
                    <fullName>Sports</fullName>
                </value>
                <value>
                    <fullName>TVs &amp; Appliances</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VisualforcePage2/src/classes/ProductsSelector.cls
public class ProductsSelector extends fflib_SObjectSelector{
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField>{
            Product__c.Id,
            Product__c.Price__c,
            Product__c.Name,    
            Product__c.Product_Code__c,
            Product__c.Type__c,
            Product__c.Product_Description__c
        };
    }
    public Schema.SObjectType getSObjectType(){
        return Product__c.SObjectType;
    }
    public Map<Id, Product__c> selectAllAsMap(){
        Map<Id, Product__c> productMap = new Map<Id, Product__c>(); 
        Database.QueryLocatorIterator iterate =  queryLocatorAllProducts().iterator();
        while(iterate.hasNext()){
            Product__c productInstance = (Product__c)iterate.next();
            productMap.put(productInstance.Id, productInstance);
        }
        return productMap;
    }
   
    public Database.QueryLocator queryLocatorAllProducts(){
       return Database.getQueryLocator(
          newQueryFactory().toSOQL()
       );
    }
    public List<Product__c> selectById(Set<ID> idSet){
        return (List<Product__c>) selectSObjectsById(idSet);
    }
    public List<Product__c> selectAll(){
        return Database.query(newQueryFactory().toSOQL());
    }
}